# Generated by Django 4.0.3 on 2022-05-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cevaplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('sinif', models.CharField(max_length=255)),
                ('ortalama', models.CharField(max_length=255)),
                ('katilim_derecesi', models.CharField(max_length=255)),
                ('hitap_eden', models.CharField(max_length=255)),
                ('hakim_misin', models.CharField(max_length=255)),
                ('dusunur_musun', models.CharField(max_length=255)),
                ('ing_duzey', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('userNo', models.CharField(max_length=255)),
            ],
        ),
    ]
